### PR TITLE
poroburu ceremony contribution #13

### PR DESCRIPTION
**Pull request by poroburu**
$ CONTRIBUTION_ID=0013_poroburu
$ CONTRIBUTION_NAME="@poroburu"
[INFO]  snarkJS: Contribution Hash:
                274e88b9 03246785 42aacc69 2c02e3a6
                5dbcb030 722a8841 1728e11e 7cd01434
                0244b9e1 6471eb6d a95458b2 dc51cb89
                3e17977a bfa58d37 76b7406b cfe15c47

### CODE REVIEW

**Comment by onewhiskeypls** [comment]
@poroburu missing the zkey file

**Comment by poroburu** [comment]
@onewhiskeypls Thank you, added the zkey file

**Comment by stepyt** [comment]
I cannot see your zkey file from your branch.

**Comment by stepyt** [comment]
> @onewhiskeypls Thank you, added the zkey file

I cannot see your zkey file from your branch

**Comment by onewhiskeypls** [comment]
verified on local, g2g

**Pull request merged**
