### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by notwheel**
added notwill

updated readme

camel had updated to 0028 after I had generated, so I had to redo mine

### CODE REVIEW

**Comment by 0xArtoss** [comment]
Hello, you need to be rebase and be position 30 please

thanks for your participation

**Comment by mahofmahof** [comment]
can i take 31

**Comment by 0xArtoss** [comment]
Yes, please take 31

**Comment by okannako** [comment]
hello,  can I take the 32 ?

**Comment by onewhiskeypls** [comment]
@notwheel you'll need to redo your contribution.

@okannako you can fork the current main branch and contribute as #32 if you get to it before notwheel does

**Comment by okannako** [comment]
i'll take 33

**Comment by okannako** [comment]
take 32

**Comment by erknfe** [comment]
@onewhiskeypls hello, can I take 33?

**Comment by 0xArtoss** [comment]
closing, please update

**Pull request closed without merging**
